---
target_miner_tag: "2021.12.14.0"
target_loki_server: "http://1.2.3.4:3100/loki/api/v1/push"
timezone: "America/Chicago"
locale: "en_US.UTF-8"
xkblayout: "us"
wifi_country: "US"
enable_gui: False
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: False
enable_vnc: False
enable_spi: True
enable_i2c: True
enable_serial: False
enable_serial_hw: True
enable_onewire: False
enable_rgpio: False