server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_SERVER}

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      miner: ${MINER_NAME}
      job: varlogs
      __path__: /host/var/log/*log

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      miner: ${MINER_NAME}
      job: containerlogs
      __path__: /host/var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<container_name>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      stream:
      container_name:
  - output:
     source: output

- job_name: miner
  pipeline_stages:
        - multiline:
            firstline: '^\d{4}-\d{2}-\d{2}\s\d{1,2}\:\d{2}\:\d{2}\.\d{3}'
            max_wait_time: 3s
  static_configs:
  - targets:
      - localhost
    labels:
      miner: ${MINER_NAME}
      job: minerlogs
      __path__: /host/home/pi/miner_data/log/console.log
