- name: create disco client directory
  file:
    path: /home/pi/disco
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: copy disco client config file
  copy:
    src: disco_config/disco.json
    dest: /home/pi/disco/
    owner: pi
    group: pi
    mode: 0644  

