- name: Miner
  import_tasks: miner.yml

- name: Grafana Agent
  import_tasks: grafana-agent.yml
  when: enable_grafana_agent == True

- name: JSON Exporter
  import_tasks: json-exporter.yml
  when: enable_json_exporter == True

- name: Docker Daemon Metrics
  import_tasks: docker-metrics.yml
  when: enable_docker_daemon_metrics == True

- name: VPN Client
  import_tasks: vpn.yml

- name: Docker
  import_tasks: docker.yml
