- name: Miner
  import_tasks: miner.yml
- name: Docker
  import_tasks: docker.yml
- name: Include OpenVPN tasks
  import_tasks: openvpn.yml
  when: openvpn_config is defined
- name: Grafana Agent
  import_tasks: grafana-agent.yml
  when: enable_grafana_agent == True