- name: create miner_aliases directory
  file:
    path: /home/pi/miner_aliases
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: create .bash_aliases
  ansible.builtin.copy: 
    src: miner_aliases/.bash_aliases
    dest: /home/pi/.bash_aliases
    owner: pi
    group: pi
    mode: 0644
  register: bash_aliases_file

- name: create /home/pi/miner_aliases/miner_aliases
  ansible.builtin.copy:
    src: miner_aliases/miner_aliases
    dest: /home/pi/miner_aliases/miner_aliases
    owner: pi
    group: pi
    mode: 0644
  register: miner_aliases_file