- name: create packet mux directory
  file:
    path: /home/pi/chirpstack-packet-multiplexer
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: create packet mux config directory
  file:
    path: /home/pi/chirpstack-packet-multiplexer/config
    state: directory
    owner: pi
    group: pi
    mode: 0755    

- name: copy mux config file
  copy:
    src: mux_config/chirpstack-packet-multiplexer.toml
    dest: /home/pi/chirpstack-packet-multiplexer/config/
    owner: pi
    group: pi
    mode: 0644  
