
- name: Install Tailscale
  import_tasks: vpn/tailscale.yml
  when: enable_tailscale == True

- name: Include OpenVPN tasks
  import_tasks: vpn/openvpn.yml
  when: openvpn_config is defined and enable_openvpn == True