all:
  children:
    eu868:
    hotspot:
      hosts: 
        myminer:
          ansible_host: 20.0.0.14 
          ansible_user: pi
          #ansible_become_pass: raspberry
          ansible_become: true
