metrics:
- name: miner_peer_book_entry_total
  path: "{ .result.peer_book_entry_count }"
  help: Miner peer book entry count 
  labels:
    miner: "{.result.name}"

- name: miner_uptime_seconds
  path: "{ .result.uptime }"
  help: Miner uptime in seconds
  labels:
    miner: "{.result.name}"

- name: miner_block_age_seconds
  path: "{ .result.block_age }"
  help: Miner block age in seconds
  labels:
    miner: "{.result.name}"

- name: miner_epoch
  path: "{ .result.epoch }"
  help: Miner epoch
  labels:
    miner: "{.result.name}"

- name: miner_height_total
  path: "{ .result.height }"
  help: Miner height total
  labels:
    miner: "{.result.name}"

- name: miner_blockchain_sync_height
  path: "{ .result.sync_height }"
  help: Blockchain Sync Height
  labels:
    miner: "{.result.name}"

body:
  content: |
    {"jsonrpc":"2.0","id":"id","method":"info_summary","params":[]}
