---
- include: raspi-facts.yml
- include: linux-facts.yml
- include: software.yml

- name: "set hostname"
  hostname:
    name: "{{ target_hostname }}.{{ target_domain }}"
  when: "target_hostname | default(false) and target_domain | default(false)"
  notify:
    - reboot

- name: "template out /etc/hosts"
  template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: "target_hostname | default(false) and target_domain | default(false)"

- name: "set timezone"
  command: "timedatectl set-timezone {{ timezone }}"
  when: "timezone | default(false) and linux_tz != timezone"

- name: "set locale"
  command: "localectl set-locale LANG={{ locale }}"
  when: "locale|default(false) and linux_locale != locale"

- name: set wifi country
  command: "raspi-config nonint do_wifi_country {{ wifi_country }}"
  when: "wifi_country | default(false) and wifi_country != raspi_wifi_country"

- include: raspi-config.yml
