global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["{{ target_hostname }}:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

remote_write:
  - url: "{{ prometheus_remote_write_endpoint }}"
    basic_auth:
      username: "{{ prometheus_remote_write_username }}"
      password: "{{ prometheus_remote_write_password }}"
